target_columns = [
    "NUMQUEST",
    "IDENT",
    "ENQU",
    "Hors_NK",
    "MOUGHATAA",
    "COMMUNE",
    "VILLAG0",
    "VILLAGE",
    "MILIEU",
    "WILAYA",
    "LATITUDE",
    "LONGITUDE",
    "ALTITUDE",
    "NUMEN",
    "DATE",
    "CDATSAISIE",
    "CODE_ENQ",
    "CODE_CONT",
    "LHG",
    "LHZ",
    "FCS",
    "CSI",
]

month_to_nb = {
    "nan": "",
    "Decembre": "12",
    "Novembre": "11",
    "Octobre": "10",
    "Septembre": "09",
    "Aout": "08",
    "Juillet": "07",
    "Juin": "06",
    "Mai": "05",
    "Avril": "04",
    "Mars": "03",
    "Fevrier": "02",
    "Janvier": "01",
}
