preprocessing_FSMS_files_with_yields_types = {
    "numquest": "float64",
    "ident": "float64",
    "enqu": "category",
    "hors nk": "category",
    "moughataa": "category",
    "commune": "category",
    "villag": "category",
    "village": "category",
    "milieu": "category",
    "wilaya": "category",
    "latitude": "float64",
    "longitude": "float64",
    "Altitude": "float64",
    "numen": "float64",
    "date": "category",
    "code enq": "category",
    "code cont": "category",
    "LHG": "category",
    "LHZ": "category",
    "fcs": "float64",
    "csi": "float64",
    "Tot_source": "float64",
    "per.source1": "float64",
    "per.source2": "float64",
    "per.source3": "float64",
    "per.source4": "float64",
    "per.source5": "float64",
    "per.source6": "float64",
    "per.source7": "float64",
    "per.source8": "float64",
    "per.source9": "float64",
    "per.source10": "float64",
    "Q9_1": "category",
    "Q9_2": "category",
    "Q9_3": "category",
    "Q9_4": "category",
    "Q9_5": "category",
    "Q9_6": "category",
    "Q9_7": "category",
    "Q9_8": "category",
    "Q9_9_162": "category",
    "Q9_9_163": "category",
    "Q9_9_164": "category",
    "Q9_9_165": "category",
    "Q9_9_166": "category",
    "Q9_9_167": "category",
    "Q9_9_168": "category",
    "Q9_9_169": "category",
    "Q9_9": "category",
    "Nb_hom": "float64",
    "Nb_fem": "float64",
    "Rap_feminité": "float64",
    "Pc_fem": "float64",
    "Dependant": "float64",
    "TxDep": "float64",
    "Equiv_ad": "float64",
    "Tailmen": "category",
    "Tailmen_range": "category",
    "Q2_5": "float64",
    "HWDDS": "float64",
    "Pondérations": "float64",
    "Extrap": "float64",
    "Trage1": "category",
    "Trage2": "category",
    "Q2_1": "category",
    "Q2_2": "float64",
    "Q2_3": "category",
    "Q2_4": "category",
    "Scol": "category",
    "Path": "category",
    "year": "int64",
    "month": "category",
    "groundnut": "float64",
    "millet": "float64",
    "sorghum": "float64",
    "maize": "float64",
    "cowpea": "float64",
    "price_id": "category",
    "Beans (niebe) - Retail": "float64",
    "Couscous - Retail": "float64",
    "Feed (flour) - Retail": "float64",
    "Feed (rakhel) - Retail": "float64",
    "Feed (wheat bran) - Retail": "float64",
    "Livestock (camel) - Retail": "float64",
    "Livestock (cattle) - Retail": "float64",
    "Livestock (goat, medium-sized male) - Retail": "float64",
    "Livestock (sheep, medium-sized castrated male) - Retail": "float64",
    "Maize (local) - Retail": "float64",
    "Meat (beef) - Retail": "float64",
    "Meat (camel) - Retail": "float64",
    "Milk (powder) - Retail": "float64",
    "Millet - Retail": "float64",
    "Oil (vegetable) - Retail": "float64",
    "Pasta (macaroni) - Retail": "float64",
    "Rice (imported) - Retail": "float64",
    "Rice (local) - Retail": "float64",
    "Sorghum (r'haya) - Retail": "float64",
    "Sorghum (red) - Retail": "float64",
    "Sorghum (taghalit) - Retail": "float64",
    "Straw - Retail": "float64",
    "Sugar - Retail": "float64",
    "Wheat - Retail": "float64",
    "Wheat flour - Retail": "float64",
    "Wheat meal - Retail": "float64",    
    "revenu1": "float64",
    "revenu2": "float64",
    "revenu3": "float64",
    "revenu_mens": "float64",
    "revenu_percap": "float64",    
}

education_level_standardization_origin = [
    "1.0",
    "0.0",
    "Oui",
    "Non",
    "Primaire et plus",
    "Niveau primaire et plus",
    "Au moins le niveau primaire",
    "Moins que le niveau primaire",
    "Aucun, coranique et Alphabétisation",
    "Non scolarisé (formel)",
]
education_level_standardization_match = [
    "1",
    "0",
    "1",
    "0",
    "1",
    "1",
    "1",
    "1",
    "0",
    "0",
]
